name: CI

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: 'Publish'

env:
  app_name: Rectangles

jobs:
  builds:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ios
            os: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Print environment variables
        run: env

      - name: 'Download development provisioning profile'
        if: matrix.name == 'ios'
        uses: apple-actions/download-provisioning-profiles@master
        with:
          bundle-id: '*'
          profile-type: 'IOS_APP_DEVELOPMENT'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
